#!/usr/bin/env python3
"""
Fish Speech TTS Wrapper
Local TTS model for voice-over generation
"""
import torch
import soundfile as sf
from pathlib import Path

class FishSpeechModel:
    def __init__(self, model_path="modelAI/fish"):
        if not Path(model_path).exists():
            model_path = "fishaudio/fish-speech-1.5"
        self.model_path = model_path
        self.llama_model = None
        self.decode_one_token = None
        self.codec_model = None
        self.device = "cuda" if torch.cuda.is_available() else "cpu"
        self.precision = torch.bfloat16
        
    def load(self):
        """Load Fish Speech models"""
        print(f"Loading Fish Speech from {self.model_path}...")
        try:
            from fish_speech.models.text2semantic.inference import init_model, load_codec_model
            
            # Find the codec/decoder checkpoint path
            model_dir = Path(self.model_path)
            codec_paths = list(model_dir.glob("*generator.pth"))
            if codec_paths:
                codec_path = str(codec_paths[0])
            else:
                codec_path = str(model_dir / "firefly-gan-vq-fbc-base-24khz-generator.pth")
                
            print(f"  Llama checkpoint: {self.model_path}")
            print(f"  Codec checkpoint: {codec_path}")
            
            # Load llama model
            self.llama_model, self.decode_one_token = init_model(
                checkpoint_path=self.model_path,
                device=self.device,
                precision=self.precision,
                compile=False
            )
            
            # Load codec model
            self.codec_model = load_codec_model(
                codec_checkpoint_path=codec_path,
                device=self.device,
                precision=self.precision
            )
            
            print("Fish Speech loaded!")
        except Exception as e:
            print(f"Error loading Fish Speech: {e}")
            raise
    
    def generate(self, text, output_path, voice="M1"):
        """Generate speech from text"""
        if self.llama_model is None or self.codec_model is None:
            self.load()
        
        print(f"  Generating speech...")
        
        from fish_speech.models.text2semantic.inference import generate_long, decode_to_audio
        
        # We generate semantic tokens using the llama model
        generator = generate_long(
            model=self.llama_model,
            device=self.device,
            decode_one_token=self.decode_one_token,
            text=text,
            max_new_tokens=0,
            top_p=0.7,
            top_k=20,
            repetition_penalty=1.2,
            temperature=0.7,
        )
        
        all_codes = []
        for response in generator:
            if response.action == "sample" and response.codes is not None:
                all_codes.append(response.codes)
                
        if not all_codes:
            raise RuntimeError("No audio semantic tokens were generated by Fish Speech.")
            
        # Concatenate generated codes across segments
        codes = torch.cat(all_codes, dim=1)
        
        # Decode codes to audio waveform
        audio_tensor = decode_to_audio(codes, self.codec_model)
        
        # Convert audio to numpy and save
        audio_np = audio_tensor.float().cpu().numpy()
        
        # Determine sample rate
        sample_rate = self.codec_model.spec_transform.sample_rate if hasattr(self.codec_model, "spec_transform") else self.codec_model.sample_rate
        
        sf.write(str(output_path), audio_np, sample_rate)
        
        duration = len(audio_np) / sample_rate
        print(f"  Saved: {output_path} ({duration:.1f}s)")
        
        return output_path

FISH_SPEECH_INFO = {
    "name": "Fish Speech 1.5",
    "vram_required": "~1-2 GB",
    "quality": "⭐⭐⭐⭐",
    "speed": "Real-time",
    "voices": ["M1", "M2", "M3", "F1", "F2", "F3"],
    "languages": ["en", "vi", "zh", "ja", "ko"],
    "license": "Open source"
}
